FRAME_RATE = 30
BULLET_LIFE_COUNT = 30
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
SCREEN_FULL_DISTANCE_SQUARED = SCREEN_WIDTH * SCREEN_WIDTH + SCREEN_HEIGHT * SCREEN_HEIGHT
ROCKET_IMAGE_WIDTH = 39
ROCKET_IMAGE_HEIGHT = 40
BULLET_IMAGE_WIDTH = 14
BULLET_IMAGE_HEIGHT = 14
ASTEROID_IMAGE_DIMENSION_SIZE_0 = 70
ASTEROID_IMAGE_DIMENSION_SIZE_1 = 90
ASTEROID_IMAGE_DIMENSION_SIZE_2 = 110
MOD_VAL = [SCREEN_WIDTH, SCREEN_HEIGHT]
ASTEROID_SPLIT_ANGLE = 15
ROCKET_HEALTH = 100
# do NOT change
ROCKET_ANGLE_ROTATION = 12
MAX_ROCKET_SPEED = 75

TICKS_TO_GENERATE_ASTEROID = 50

PLAYER_ONE_COLOR = (237, 28, 36)
PLAYER_TWO_COLOR = (0, 162, 232)

COLOR_BLACK = (0, 0, 0)

BULLET_RADIUS_RATIO = 0.7
ASTEROID_RADIUS_RATIO = 0.35
ROCKET_RADIUS_RATIO = 0.35

INACTIV_STEPS_LIMIT = 0
INACTIVE_EVASION_TIME_LIMIT = -1
INACTIVE_SMART_TIME_LIMIT = 0
IMPACT_RADIUS = 30

NOT_FOUND_STEPS_COUNT = 100

RANDOM_SEED = 120

VISUAL = True
ROCKET_ONE_INVULNERABLE = False
ROCKET_TWO_INVULNERABLE = False

BULLET_ASTEROID_COLLISION_REWARD = 5
ASTEROID_ROCKET_COLLISION_REWARD = 20
ASTEROID_ROCKET_COLLISION_PENALTY = -10